print("If you could transfer your conscience into a robot, would you?")
print("Can you tell I'm having a lot of fun? I am!")
print("Dolly Parton once said, \"You'll never do a whole lot unless you're brave enough to try.\" ")
print("I like that coding tests your resolve and willingness to keep trying.")
print("I wonder how many coders just talk to themselves like this. Hello, Professor if you read these.")